### ISSUE TITLE
clear: error while loading shared libraries: libc.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by leapofazzam123** [Maxython/arch-packages-for-termux#3]

**Comment by Maxython** [comment]
The `clear` command needs access to conflicting libraries.  The `asl` command gives access to these libraries.  
```
asl clear
```

If you need access without `asl`, activate the arch shell (example: `asl bash`). But if you need shell access from termux, then you can use `alias`.  
```
alias clear="asl clear"
```
